### PR TITLE
Check length of polynomials

### LINKED ISSUE #87: Check polynomial lengths
Incorrect polynomial lengths will trigger `panic` if too short or lead to failed signatures if too long.  Check for this during DKG, and also during `Aggregator::init` in case something slips through.

### PR DESCRIPTION
**Pull request by xoloki**
This change fixes a DoS that results from incorrectly sized polynomials.  A polynomial that is too large will result in signatures that fail to verify, and one that is too small will lead to a `panic` when initializing the signature aggregator.

Fixes #87

### CODE REVIEW

File: src/v1.rs [hunk 1]
```diff
@@ -370,17 +372,18 @@ impl traits::Aggregator for Aggregator {
 
     /// Initialize the Aggregator polynomial
     fn init(&mut self, comms: &HashMap<u32, PolyCommitment>) -> Result<(), AggregatorError> {
+        let threshold = self.threshold.try_into().unwrap();
```
Comment (djordon) [inline src/v1.rs:375]: Why `unwrap()` here?

Well my thinking is that if it can panic, then unwrapping is bad. If it cannot panic, then you should probably explain why in a comment and do an `as usize` cast. Like, if `threshold` is a `u32` then the `as usize` cast is always fine on machines that this library supports and I'd just say that. Alternatively, you could just add a variant to the `AggregatorError` for the conversion error and `?`.

File: src/v2.rs [hunk 2]
```diff
@@ -115,12 +115,14 @@ impl Party {
...
+        let threshold: usize = self.threshold.try_into().unwrap();
         let mut bad_ids = Vec::new();
         for (i, comm) in comms.iter() {
-            if !comm.verify() {
+            if comm.poly.len() != threshold || !comm.verify() {
                 bad_ids.push(*i);
+            } else {
+                self.group_key += comm.poly[0];
             }
-            self.group_key += comm.poly[0];
```
Comment (djordon) [inline src/v2.rs:123]: Oh good catch.

File: src/errors.rs [hunk 3]
```diff
@@ -36,10 +36,10 @@ impl From<PointError> for DkgError {
 /// Errors which can happen during signature aggregation
 pub enum AggregatorError {
     #[error("bad poly commitment length (expected {0} got {1})")]
-    /// The polynomial commitment was the wrong size
+    /// The number of polynomial commitments was wrong (no longer used)
```
Comment (djordon) [inline src/errors.rs:39]: Ohh, this is not removed because it's breaking change right?

**Review by djordon — COMMENTED** [review]
The logic looks good, but shouldn't we add tests here too?

File: src/v1.rs (hunk 1 above)
Comment (xoloki) [reply src/v1.rs:375]: `usize` is not always bigger than `u32`, so this can fail. But as @jferrant  discovered last year, if`as usize` casts fail they do so silently 😳

So now we always do try/unwrap.

File: src/errors.rs (hunk 3 above)
Comment (xoloki) [reply src/errors.rs:39]: Exactly

File: src/v1.rs (hunk 1 above)
Comment (djordon) [reply src/v1.rs:375]: Oh interesting. Well in that case why would you panic here? Why not just bubble up the error and have the caller handler it if they want?

---
Side note. I thought that on "regular" machines, like machines where the CPU instruction set defaults to 64bit or 32bit "words" (I forget the proper term), that `usize` will be at least 32 bits. Also, I thought that the `as` casts just reinterprets the bits, so a failure "just" means that the number isn't what you thought it was. Is that what you mean by silent failure?

Comment (xoloki) [reply src/v1.rs:375]: I think @jferrant ’s logic was basically: this will almost certainly never fail. But if it does, it means something terribly wrong has happened, so let’s make sure we notice it by panicking. 

And yes, that’s what we mean by silent failure here.

File: src/v2.rs (hunk 2 above)
Comment (xoloki) [reply src/v2.rs:123]: Thanks

File: src/v1.rs (hunk 1 above)
Comment (xoloki) [reply src/v1.rs:375]: The reason not to bubble up is the sheer number of these present after we switched to using u32/u64. Previously we used usize over the network which was super sketchy.

**Comment by xoloki** [comment]
> The logic looks good, but shouldn't we add tests here too?

Indeed, I’ll add some tomorrow

**Comment by xoloki** [comment]
Ok @djordon new generic test added and called from `v1` and `v2`.

File: src/v1.rs (hunk 1 above)
Comment (xoloki) [reply src/v1.rs:375]: Actually the number is not too large; only 26 sites, some of which are in functions that already return Result, and other in test code.  I'll add an issue to take care of the low hanging fruit.

Comment (xoloki) [reply src/v1.rs:375]: Tracking this work in #89

Comment (xoloki) [reply src/v1.rs:375]: PR is up, though it should go in after this one since it will need to handle the unwraps here: #91

File: src/v1.rs [hunk 4]
```diff
@@ -149,12 +149,14 @@ impl Party {
...
         self.group_key = Point::zero();
 
+        let threshold: usize = self.threshold.try_into().unwrap();
         let mut bad_ids = Vec::new(); //: Vec<u32> = polys
         for (i, comm) in polys.iter() {
-            if !comm.verify() {
+            if comm.poly.len() != threshold || !comm.verify() {
                 bad_ids.push(*i);
+            } else {
+                self.group_key += comm.poly[0];
```
Comment (djordon) [inline src/v1.rs:158]: I know this was here before, but can `poly` this ever be empty?

File: src/traits.rs [hunk 5]
```diff
@@ -153,6 +153,41 @@ pub mod test_helpers {
 
     use crate::{common::PolyCommitment, errors::DkgError};
 
+    #[allow(non_snake_case)]
```
Comment (djordon) [inline src/traits.rs]: I don't think this function needs this.

**Review by djordon — APPROVED** [review]
Looks good.

Suppose at the end of all of this, there is a bad party member who uses an incorrect polynomial length. Does WSTS associate the party id to their public key or is that all left to the caller?

File: src/v1.rs (hunk 4 above)
Comment (xoloki) [reply src/v1.rs:158]: An old PR from @hstove that's still around discusses how to handle a threshold of `0` (#55).

File: src/traits.rs (hunk 5 above)
Comment (xoloki) [reply src/traits.rs]: Nope, remove it and the one below.

File: src/v1.rs (hunk 4 above)
Comment (xoloki) [reply src/v1.rs:158]: I think we should just `panic` on a `threshold` of `0`.

**Comment by xoloki** [comment]
> Looks good.
> 
> Suppose at the end of all of this, there is a bad party member who uses an incorrect polynomial length. Does WSTS associate the party id to their public key or is that all left to the caller?

Oh, very good question.  It looks like `SignerStateMachine` was trying to be clever, and looked for bad public shares before calling `compute_secrets`.  This allowed it to handle both `v1` and `v2`, since in the `v1` case we need to associate the `party_id` with a `signer_id`.

So we need to check that the poly length equals the threshold there too.

**Comment by xoloki** [comment]
Thinking about this more, maybe we shouldn't do a separate check for `BadPublicShares`, and just let it fall out of `compute_secrets` like `BadPrivateShares`:

Here's the duplicated `BadPublicShares` check:
https://github.com/Trust-Machines/wsts/blob/main/src/state_machine/signer/mod.rs#L346
https://github.com/Trust-Machines/wsts/blob/main/src/state_machine/signer/mod.rs#L371

Here's the actual `compute_secrets` call which only handles `BadPrivateShares`:
https://github.com/Trust-Machines/wsts/blob/main/src/state_machine/signer/mod.rs#L400

Here's where we map the `party_id` to a `signer_id`:
https://github.com/Trust-Machines/wsts/blob/main/src/state_machine/signer/mod.rs#L405

Thoughts?

**Comment by xoloki** [comment]
I went ahead and fixed it in the separate check, then added a test.  Are you okay with merging as is @djordon ?

File: src/traits.rs [hunk 6]
```diff
@@ -220,4 +253,44 @@ pub mod test_helpers {
...
+        let Np: u32 = 4;
+        let T: u32 = 7;
+        let signer_ids: Vec<Vec<u32>> = vec![vec![1, 2, 3], vec![4, 5], vec![6, 7, 8, 9], vec![10]];
+        let mut rng = OsRng;
+        let mut signers: Vec<Signer> = signer_ids
+            .iter()
+            .enumerate()
+            .map(|(id, ids)| {
+                if *ids == vec![10] {
+                    Signer::new(id.try_into().unwrap(), ids, Nk, Np, T - 1, &mut rng)
```
Comment (technovision99) [inline src/traits.rs]: Thanks for adding this, but could you also add a test for the case where a malicious signer creates a polynomial whose degree is greater than the threshold?

Comment (xoloki) [reply src/traits.rs]: Done @technovision99

File: src/v1.rs [hunk 7]
```diff
@@ -825,4 +829,14 @@ mod tests {
     pub fn run_compute_secrets_missing_shares() {
         run_compute_secrets_not_enough_shares::<v1::Signer>()
     }
+
+    #[allow(non_snake_case)]
+    #[test]
+    /// Run DKG and aggregator init with a bad polynomial
+    pub fn bad_polynomial_length() {
+        let gt = |t| t + 1;
+        let lt = |t| t + 1;
```
Comment (djordon) [inline src/v1.rs]: These are the same functions.

File: src/v2.rs [hunk 8]
```diff
@@ -714,10 +718,18 @@ mod tests {
...
     /// Run a distributed key generation round with not enough shares
     pub fn run_compute_secrets_missing_shares() {
         run_compute_secrets_not_enough_shares::<v2::Signer>()
     }
+
+    #[test]
+    /// Run DKG and aggregator init with a bad polynomial
+    pub fn bad_polynomial_length() {
+        let gt = |t| t + 1;
+        let lt = |t| t + 1;
```
Comment (djordon) [inline src/v2.rs]: These are also the same functions.

File: src/v1.rs (hunk 7 above)
Comment (xoloki) [reply src/v1.rs]: Fixed.

File: src/v2.rs (hunk 8 above)
Comment (xoloki) [reply src/v2.rs]: Fixed.
