### PR TITLE
Optimistically aggregate the group signature

### LINKED ISSUE #51: Optimize `Aggregator::sign` by optimistically aggregating
Currently, `Aggregator::sign` will verify all of the signature shares *before* aggregating.  But we later verify the aggregate signature as well.  

Since the aggregate signature will fail to verify if any of the signature shares are bad, there is no reason to do the expensive signature share check first.  Instead do the aggregation and verify the resulting signature; if it's good, great.  If not, then do the expensive check and find out which shares were bad.

### PR DESCRIPTION
**Pull request by xoloki**
One of the design principles of `FROST` is to optimize the performance of the protocol for the optimistic case where all participants are honest.  This is a good design choice for a cryptocurrency context, because dishonest participants can be readily identified, and sanctioned in ways to severely disincentivize such behavior.

Recently we have focused on performance of the signing part of the protocol, to allow for a large group signature (hundreds of parties controlling thousands of keys) in a matter of seconds.  This is necessary, for example, to enable 5 second block times in `PoS` style cryptocurrency systems, where all staked actors participate in a threshold signature over the block.

Prior to this PR, during the signature aggregation phase of signing we checked all signature shares before aggregation.  However, doing so involved many large multiexponentiations, with the number of such on the order of the number of parties, and the magnitude on the order of the threshold.   

If we think of the security properties of a `FROST`, or any `Schnorr` signature, we know that these include `soundness`, where a signature will fail validation with some computationally high probability if the parties making it do not have valid witnesses.  So to determine that a signature is valid, it is not necessary to check the individual signature shares; simply checking that the aggregate signature itself is valid will demonstrate this quite adequately.  

If the aggregate signature fails validation, it will still be necessary to check the signatures shares individually, in order to determine which actors are malicious.  But since aggregating and checking the group signature is computationally trivial, we lose nothing in the failure case, and improve our performance by multiple orders of magnitude in the optimistic case.  

Fixes #51

### CODE REVIEW

File: src/v2.rs [hunk 1]
```diff
@@ -269,23 +269,59 @@ pub struct Aggregator {
...
-    /// Check and aggregate the party signatures
+    /// Aggregate the party signatures using a tweak
     #[allow(non_snake_case)]
     pub fn sign_with_tweak(
         &mut self,
         msg: &[u8],
         nonces: &[PublicNonce],
         sig_shares: &[SignatureShare],
-        key_ids: &[u32],
+        _key_ids: &[u32],
```
Comment (jferrant) [inline src/v2.rs:279]: Did you decide against changing the function signature to avoid a major release?

**Review by jferrant — APPROVED** [review]
Just the one comment. But looks good to me :D

File: src/v2.rs (hunk 1 above)
Comment (xoloki) [reply src/v2.rs:279]: Yes exactly.
