### PR TITLE
Fix bad public shares check

### LINKED ISSUE #105: Coordinator does not check threshold when verifying BadPublicShares
When the signers are checking the `DkgPublicShares` from other signers, they check both that the Schnorr signature and the threshold (which determines the degree of the polynomial) are correct.

However, when the coordinator verifies the BadPublicShares report, it only checks the Schnorr signature, not the polynomial degree.

### PR DESCRIPTION
**Pull request by xoloki**
We saw an issue on `sBTC` testnet where a single signer with a bad threshold not only prevented `DKG` from completing, but also caused the `Coordinator` to think that all signers were malicious.  This was because the signers were checking the threshold when evaluating `DkgPublicShares`, but the `Coordinator` was not.

To fix this, move the public shares check to common code, and call it from everywhere.  

Fixes #105

### CODE REVIEW

File: src/state_machine/coordinator/fire.rs [hunk 1]
```diff
@@ -568,7 +568,7 @@ impl<Aggregator: AggregatorTrait> Coordinator<Aggregator> {
         }
 
         let mut dkg_failures = HashMap::new();
-
+        let threshold: usize = self.config.threshold.try_into().unwrap();
```
Comment (djordon) [inline src/state_machine/coordinator/fire.rs:571]: Can't we use `?` instead of `unwrap`?

**Review by djordon — COMMENTED** [review]
We should add a test here too.

File: src/state_machine/coordinator/fire.rs (hunk 1 above)
Comment (xoloki) [reply src/state_machine/coordinator/fire.rs:571]: Only if we add TryFromInt to the coordinator Error, which is a major api rev. I added it on the other PR.

**Review by jferrant — APPROVED** [review]
